import { DashboardData, EmployeeDetail } from "@/types/dashboard";

export const MOCK_DASHBOARD_DATA: DashboardData = {
  kpis: {
    recoverableHours: 245.5,
    recoverableCost: 386400,
    totalEmployees: 48,
    totalActivities: 18450,
  },
  filters: {
    departments: [
      "Engineering",
      "Customer Operations",
      "Finance & Accounting",
      "Human Resources",
      "Sales & Marketing",
    ],
    employees: [
      { id: "EMP-101", name: "Aarav Mehta", department: "Engineering" },
      { id: "EMP-102", name: "Ananya Iyer", department: "Customer Operations" },
      { id: "EMP-103", name: "Devendra Singh", department: "Finance & Accounting" },
      { id: "EMP-104", name: "Isha Sharma", department: "Human Resources" },
      { id: "EMP-105", name: "Kabir Gupta", department: "Sales & Marketing" },
      { id: "EMP-106", name: "Meera Nair", department: "Customer Operations" },
      { id: "EMP-107", name: "Pranav Rao", department: "Engineering" },
      { id: "EMP-108", name: "Rohan Verma", department: "Finance & Accounting" },
    ],
    dateRanges: [
      { label: "Last 30 Days", start: "2026-06-30", end: "2026-07-30" },
      { label: "Last 7 Days", start: "2026-07-23", end: "2026-07-30" },
      { label: "This Month", start: "2026-07-01", end: "2026-07-30" },
      { label: "Last Quarter", start: "2026-04-01", end: "2026-06-30" },
    ],
    taskCategories: [
      "Manual Data Entry",
      "Report Generation",
      "Email Management",
      "Document Verification",
      "Meeting Coordination",
    ],
  },
  timeByDepartment: [
    { department: "Engineering", hours: 42.5, cost: 85000 },
    { department: "Customer Operations", hours: 88.0, cost: 123200 },
    { department: "Finance & Accounting", hours: 62.0, cost: 111600 },
    { department: "Human Resources", hours: 22.5, cost: 31500 },
    { department: "Sales & Marketing", hours: 30.5, cost: 35100 },
  ],
  timeByApp: [
    { appName: "Microsoft Outlook", hours: 75.0, percentage: 31 },
    { appName: "SAP ERP System", hours: 55.0, percentage: 22 },
    { appName: "Microsoft Excel", hours: 48.0, percentage: 20 },
    { appName: "Salesforce CRM", hours: 32.0, percentage: 13 },
    { appName: "Google Chrome", hours: 21.0, percentage: 9 },
    { appName: "Slack Messenger", hours: 14.5, percentage: 5 },
  ],
  timeByTaskCategory: [
    { category: "Manual Data Entry", hours: 92.5 },
    { category: "Email Management", hours: 61.0 },
    { category: "Report Generation", hours: 45.0 },
    { category: "Document Verification", hours: 31.0 },
    { category: "Meeting Coordination", hours: 16.0 },
  ],
  weeklyTrend: [
    { week: "Wk 27", productiveHours: 1540, recoverableHours: 268 },
    { week: "Wk 28", productiveHours: 1610, recoverableHours: 254 },
    { week: "Wk 29", productiveHours: 1580, recoverableHours: 248 },
    { week: "Wk 30", productiveHours: 1620, recoverableHours: 245.5 },
  ],
  automationTasks: [
    {
      rank: 1,
      taskName: "Manual CSV Upload to SAP ERP",
      hours: 58.5,
      employeeCount: 12,
      estimatedSavings: 115000,
      priority: "High",
    },
    {
      rank: 2,
      taskName: "Customer Support Email Sorting",
      hours: 44.0,
      employeeCount: 8,
      estimatedSavings: 82000,
      priority: "High",
    },
    {
      rank: 3,
      taskName: "Monthly Compliance PDF Creation",
      hours: 38.0,
      employeeCount: 4,
      estimatedSavings: 68000,
      priority: "Medium",
    },
    {
      rank: 4,
      taskName: "CRM Lead Source Deduplication",
      hours: 28.5,
      employeeCount: 7,
      estimatedSavings: 45000,
      priority: "Medium",
    },
    {
      rank: 5,
      taskName: "Candidate Interview Rescheduling",
      hours: 21.0,
      employeeCount: 3,
      estimatedSavings: 28000,
      priority: "Low",
    },
  ],
  employees: [
    {
      id: "EMP-101",
      name: "Aarav Mehta",
      email: "aarav.mehta@workforcepulse.com",
      department: "Engineering",
      role: "Lead Software Architect",
      totalHours: 168.0,
      recoverableHours: 12.5,
      recoverableCost: 31250,
      efficiencyScore: 92,
    },
    {
      id: "EMP-102",
      name: "Ananya Iyer",
      email: "ananya.iyer@workforcepulse.com",
      department: "Customer Operations",
      role: "Senior Support Executive",
      totalHours: 172.0,
      recoverableHours: 28.0,
      recoverableCost: 39200,
      efficiencyScore: 83,
    },
    {
      id: "EMP-103",
      name: "Devendra Singh",
      email: "devendra.singh@workforcepulse.com",
      department: "Finance & Accounting",
      role: "Principal Accountant",
      totalHours: 165.0,
      recoverableHours: 24.5,
      recoverableCost: 44100,
      efficiencyScore: 85,
    },
    {
      id: "EMP-104",
      name: "Isha Sharma",
      email: "isha.sharma@workforcepulse.com",
      department: "Human Resources",
      role: "HR Generalist",
      totalHours: 160.0,
      recoverableHours: 14.0,
      recoverableCost: 19600,
      efficiencyScore: 91,
    },
    {
      id: "EMP-105",
      name: "Kabir Gupta",
      email: "kabir.gupta@workforcepulse.com",
      department: "Sales & Marketing",
      role: "Campaign Strategist",
      totalHours: 170.0,
      recoverableHours: 18.5,
      recoverableCost: 24050,
      efficiencyScore: 89,
    },
    {
      id: "EMP-106",
      name: "Meera Nair",
      email: "meera.nair@workforcepulse.com",
      department: "Customer Operations",
      role: "Operations Associate",
      totalHours: 176.0,
      recoverableHours: 32.5,
      recoverableCost: 45500,
      efficiencyScore: 81,
    },
    {
      id: "EMP-107",
      name: "Pranav Rao",
      email: "pranav.rao@workforcepulse.com",
      department: "Engineering",
      role: "Frontend Engineer",
      totalHours: 166.0,
      recoverableHours: 16.0,
      recoverableCost: 28000,
      efficiencyScore: 90,
    },
    {
      id: "EMP-108",
      name: "Rohan Verma",
      email: "rohan.verma@workforcepulse.com",
      department: "Finance & Accounting",
      role: "Billing Analyst",
      totalHours: 168.0,
      recoverableHours: 22.0,
      recoverableCost: 35200,
      efficiencyScore: 86,
    },
  ],
};

export const MOCK_EMPLOYEE_DETAILS: Record<string, EmployeeDetail> = {
  "EMP-101": {
    id: "EMP-101",
    name: "Aarav Mehta",
    email: "aarav.mehta@workforcepulse.com",
    department: "Engineering",
    role: "Lead Software Architect",
    kpis: {
      recoverableHours: 12.5,
      recoverableCost: 31250,
      totalActivities: 520,
    },
    activitySummary: [
      { appName: "VS Code", hours: 68.0 },
      { appName: "GitHub Enterprise", hours: 38.0 },
      { appName: "Jira Software", hours: 22.0 },
      { appName: "Microsoft Outlook", hours: 18.0 },
      { appName: "Slack Messenger", hours: 12.0 },
    ],
    topRepetitiveTasks: [
      { taskName: "Manual Release Notes Compilation", hours: 7.5, frequency: 4 },
      { taskName: "Jira Board Status Syncing", hours: 5.0, frequency: 15 },
    ],
    weeklyTrend: [
      { week: "Wk 27", hours: 14.5 },
      { week: "Wk 28", hours: 11.0 },
      { week: "Wk 29", hours: 13.5 },
      { week: "Wk 30", hours: 12.5 },
    ],
  },
  "EMP-102": {
    id: "EMP-102",
    name: "Ananya Iyer",
    email: "ananya.iyer@workforcepulse.com",
    department: "Customer Operations",
    role: "Senior Support Executive",
    kpis: {
      recoverableHours: 28.0,
      recoverableCost: 39200,
      totalActivities: 1240,
    },
    activitySummary: [
      { appName: "Salesforce Service Cloud", hours: 72.0 },
      { appName: "Microsoft Outlook", hours: 44.0 },
      { appName: "Internal Knowledge Base", hours: 26.0 },
      { appName: "Microsoft Teams", hours: 20.0 },
      { appName: "Google Chrome", hours: 10.0 },
    ],
    topRepetitiveTasks: [
      { taskName: "Sorting Support Queries", hours: 16.5, frequency: 180 },
      { taskName: "Copy-pasting Customer IDs", hours: 11.5, frequency: 220 },
    ],
    weeklyTrend: [
      { week: "Wk 27", hours: 31.0 },
      { week: "Wk 28", hours: 29.5 },
      { week: "Wk 29", hours: 26.0 },
      { week: "Wk 30", hours: 28.0 },
    ],
  },
};
